test pipeline

diff --git a/.github/workflows/user-cd.yml b/.github/workflows/user-cd.yml
--- a/.github/workflows/user-cd.yml
+++ b/.github/workflows/user-cd.yml
@@ -4,7 +4,7 @@ on:
   push:
     paths:
       - 'User/**'
-      - '.github/workflows/user-api-cd.yml'
+      - '.github/workflows/user-cd.yml'
   workflow_dispatch:
 
 jobs:
@@ -19,7 +19,14 @@ jobs:
           version: 'latest'
 
       - name: Docker login
-        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
+        run: |
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ] || [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
+            echo "One or both Docker secrets are missing!"
+            exit 1
+          fi
+
+          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+
 
       - name: Pull latest User API image
         run: docker pull gyliana/user-api:latest
